---

- name: Destroy VM
  hosts: localhost
  vars:
    vm_name: "mann-uloha"
  tasks:
    - name: Deleting misc files
      ansible.builtin.file:
        path: "{{ playbook_dir }}/vm/{{ item }}"
        state: absent
      with_items:
        - cidata.iso
        - user-data
        - meta-data
        - known_hosts
        - id_ed25519
        - id_ed25519.pub
    # we keep clean.qcow2 (so that we don't have to download it again)

    - name: Destroying VM
      community.libvirt.virt:
        name: "{{ vm_name }}"
        state: destroyed

    - name: Undefine VM
      community.libvirt.virt:
        name: "{{ vm_name }}"
        command: undefine

    - name: Deleting disk
      ansible.builtin.file:
        path: "{{ playbook_dir }}/vm/disk.qcow2"
        state: absent
